name = "LeanGO"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["LeanGO"]

[leanOptions]
pp.unicode.fun = true                 # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "LeanGO"

[[lean_lib]]
name = "Manual"
srcDir = "LeanGO/verso/"
root = "Manual"

[[lean_exe]]
name = "manual"
srcDir = "LeanGO/verso/"
root = "Manual"
